# Generated by Django 4.2.3 on 2023-08-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykefrontedmenus',
            options={'ordering': ['sort'], 'verbose_name': 'BaykeFrontedMenus', 'verbose_name_plural': 'BaykeFrontedMenus'},
        ),
    ]
