# Generated by Django 4.2.3 on 2023-08-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeEmailConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('email_host', models.CharField(default='smtp.qq.com', max_length=50, verbose_name='邮箱发送后端')),
                ('email_host_user', models.EmailField(help_text='用于发送邮件的邮箱地址', max_length=150, verbose_name='发送邮箱号')),
                ('email_host_password', models.CharField(help_text='自己的邮箱密码，或授权码，一般现在的邮箱都需要授权码', max_length=80, verbose_name='邮箱登录密码或授权码')),
                ('email_port', models.PositiveSmallIntegerField(default=465, help_text='QQ邮箱一般为465', verbose_name='邮箱服务器端口号')),
                ('email_use_ssl', models.BooleanField(default=True, verbose_name='是否为隐式安全连接')),
                ('default_from_email', models.EmailField(blank=True, default='', max_length=150, verbose_name='发送邮件默认邮箱')),
                ('status', models.BooleanField(default=True, verbose_name='开启状态')),
            ],
            options={
                'verbose_name': 'BaykeEmailConf',
                'verbose_name_plural': 'BaykeEmailConfs',
            },
        ),
        migrations.CreateModel(
            name='BaykeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('site_title', models.CharField(default='baykeshop商城系统', max_length=50, verbose_name='站点名称')),
                ('logo_url', models.URLField(verbose_name='logo地址')),
                ('copyright', models.CharField(blank=True, default='baykeshop版权所有', max_length=150, verbose_name='版权信息')),
            ],
            options={
                'verbose_name': 'BaykeSystem',
                'verbose_name_plural': 'BaykeSystems',
            },
        ),
        migrations.CreateModel(
            name='BaykeSystemExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('key', models.SlugField(max_length=150, verbose_name='key')),
                ('value', models.CharField(blank=True, default='', max_length=200, verbose_name='字符串值')),
                ('title', models.CharField(max_length=80, verbose_name='配置标题')),
            ],
            options={
                'verbose_name': 'BaykeSystemExtend',
                'verbose_name_plural': 'BaykeSystemExtends',
                'ordering': ['-add_date'],
            },
        ),
        migrations.RemoveField(
            model_name='baykeconfoptions',
            name='category',
        ),
        migrations.DeleteModel(
            name='BaykeConfCategory',
        ),
        migrations.DeleteModel(
            name='BaykeConfOptions',
        ),
    ]
