# Generated by Django 4.2.4 on 2023-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmin', '0002_baykeverifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='余额'),
        ),
    ]
