# Generated by Django 4.2.3 on 2023-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmin', '0003_baykepermissionaction_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykepermissionaction',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='备注'),
        ),
    ]
