# Generated by Django 4.2.4 on 2023-08-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badmin', '0003_baykeuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykepermissionaction',
            name='menus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badmin.baykefrontedmenus', verbose_name='菜单'),
        ),
    ]
