site_name: BaykeShop Docs
site_url: http://www.bayke.shop/
# repo_url: https://github.com/example/repository/
site_description: "baykeShop（拜客商城系统使用文档）"
site_author: "幸福关中"

nav: 
    - 首页: index.md
    - 开发文档: code/index.md
    - 后台操作: 
        - 后台自定义菜单: menus.md
        - 商品模块: 
            - 商品分类: shop/category.md
            - 商品规格: shop/spec.md
            - 商品管理: shop/product.md
            - 商品评价: shop/comment.md
        - 订单管理: shop/order.md
# theme: readthedocs
extra:
    version: v1.0

