# Generated by Django 4.2.4 on 2023-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopcomment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baykeshopcomment',
            name='tag',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='标记'),
        ),
    ]
