# Generated by Django 4.2.4 on 2023-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_baykeshopcomment_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopcomment',
            name='reply',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='回复内容'),
        ),
    ]
