# Generated by Django 4.2.4 on 2023-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_baykeuserbalancelog_baykeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='baykeshoporder',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='签收人'),
        ),
        migrations.AlterField(
            model_name='baykeshoporder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='手机号'),
        ),
    ]
