# Generated by Django 4.2.4 on 2023-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_baykeshoporder_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopordersku',
            name='is_commented',
            field=models.BooleanField(default=False, verbose_name='是否已评价'),
        ),
    ]
