# Generated by Django 4.2.3 on 2023-08-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_baykeshopbrand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopbrand',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='shop/brand/', verbose_name='品牌logo'),
        ),
    ]
