# Generated by Django 4.2.4 on 2023-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_baykeshopordersku_is_commented'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='删除标记')),
                ('img', models.ImageField(upload_to=None)),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('target', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
            ],
            options={
                'verbose_name': 'BaykeShopBanner',
                'verbose_name_plural': 'BaykeShopBanners',
                'ordering': ['-add_date'],
            },
        ),
    ]
