# Generated by Django 4.2.4 on 2023-08-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_baykeshopbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopbanner',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='baykeshopbanner',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
