# Generated by Django 4.2.4 on 2023-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_baykeshopbanner_sort_baykeshopbanner_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeshopbanner',
            options={'ordering': ['sort', '-add_date'], 'verbose_name': 'BaykeShopBanner', 'verbose_name_plural': 'BaykeShopBanners'},
        ),
        migrations.AlterField(
            model_name='baykeshopbanner',
            name='img',
            field=models.ImageField(upload_to='banner'),
        ),
    ]
