# Generated by Django 4.2.3 on 2023-08-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_baykeshopsku_unit_baykeshopspu_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeshopspu',
            options={'ordering': ['-sort', '-add_date'], 'verbose_name': 'BaykeShopSPU', 'verbose_name_plural': 'BaykeShopSPUs'},
        ),
        migrations.AddField(
            model_name='baykeshopsku',
            name='status',
            field=models.BooleanField(default=True, verbose_name='商品状态(上下架)'),
        ),
        migrations.AddField(
            model_name='baykeshopspu',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='baykeshopspu',
            name='status',
            field=models.BooleanField(default=True, verbose_name='商品状态(上下架)'),
        ),
    ]
