# Generated by Django 4.2.3 on 2023-08-07 10:22

import baykeshop.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_baykeshopspu_options_baykeshopsku_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopsku',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='售价'),
        ),
        migrations.AddField(
            model_name='baykeshopsku',
            name='item',
            field=models.CharField(blank=True, max_length=50, verbose_name='商品编号'),
        ),
        migrations.AddField(
            model_name='baykeshopsku',
            name='vol',
            field=models.FloatField(blank=True, default=0, verbose_name='体积'),
        ),
        migrations.AddField(
            model_name='baykeshopsku',
            name='weight',
            field=models.FloatField(blank=True, default=0, verbose_name='重量'),
        ),
        migrations.AddField(
            model_name='baykeshopspu',
            name='skutype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '单规格'), (1, '多规格')], default=0, verbose_name='规格类型'),
        ),
        migrations.AlterField(
            model_name='baykeshopsku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='baykeshopsku',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='baykeshopspu',
            name='images',
            field=models.JSONField(blank=True, default=list, validators=[baykeshop.common.validators.validate_count], verbose_name='轮播图'),
        ),
    ]
