# Generated by Django 4.2.3 on 2023-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_baykeshopsku_cost_price_baykeshopsku_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopspu',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='baykeshopspu',
            name='freighttype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '固定运费'), (1, '运费模板')], default=0, verbose_name='运费类型'),
        ),
    ]
