# Generated by Django 4.2.3 on 2023-08-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_baykeshopspu_freight_baykeshopspu_freighttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopspu',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='商品简介'),
        ),
        migrations.AddField(
            model_name='baykeshopspu',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='商品关键字'),
        ),
    ]
