# Generated by Django 4.2.3 on 2023-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_baykeshopspu_desc_baykeshopspu_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopspu',
            name='expresstype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '快递'), (1, '上门自提')], default=0, verbose_name='运费类型'),
        ),
        migrations.AlterField(
            model_name='baykeshopsku',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='成本价'),
        ),
    ]
