# Generated by Django 4.2.3 on 2023-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_baykeshopspu_expresstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopspec',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='baykeshopspec',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
