# Generated by Django 4.2.3 on 2023-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_baykeshopspec_sort_baykeshopspec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopsku',
            name='img',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='主图'),
        ),
    ]
