# Generated by Django 4.2.3 on 2023-08-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_baykeshopsku_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporder',
            name='paymethod',
            field=models.PositiveSmallIntegerField(choices=[(None, '(Unknown)'), (1, '支付宝支付'), (2, '微信支付'), (3, '余额支付')], default='(Unknown)', verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='baykeshoporder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成'), (6, '已关闭'), (7, '退款中')], default=1, verbose_name='订单状态'),
        ),
    ]
