# Generated by Django 4.2.3 on 2023-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_baykeshoporder_paymethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporder',
            name='order_sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='baykeshoporder',
            name='paymethod',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '(Unknown)'), (1, '支付宝支付'), (2, '微信支付'), (3, '余额支付')], null=True, verbose_name='支付方式'),
        ),
    ]
