# Generated by Django 4.2 on 2023-05-04 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeshop', '0002_baykeshopaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaykeShopAddress',
            new_name='BaykeAddress',
        ),
    ]
