# Generated by Django 4.2 on 2023-05-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0003_rename_baykeshopaddress_baykeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeuser',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='描述'),
        ),
    ]
