# Generated by Django 4.2 on 2023-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0005_baykeordercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeproductsku',
            name='options',
            field=models.ManyToManyField(blank=True, to='baykeshop.baykeproductspecoption', verbose_name='规格值'),
        ),
    ]
